export enum CODES {
  FAIL = 'FAIL',
  SUCCESS = 'SUCCESS',
  GET_CHEST_FAIL = 'GET_CHEST_FAIL',
  GET_THING_FAIL = 'GET_THING_FAIL',
  JOIN_CHEST_FAIL = 'JOIN_CHEST_FAIL',
  GET_CHESTS_FAIL = 'GET_CHESTS_FAIL',
  GET_THINGS_FAIL = 'GET_THINGS_FAIL',
  LEAVE_CHEST_FAIL = 'LEAVE_CHEST_FAIL',
  CREATE_THING_FAIL = 'CREATE_THING_FAIL',
  CREATE_CHEST_FAIL = 'CREATE_CHEST_FAIL',
  UPDATE_THING_FAIL = 'UPDATE_THING_FAIL',
  CREATE_OPERATION_FAIL = 'CREATE_OPERATION_FAIL',
  AUTH_FAIL_WRONG_CREDENTIAL = 'AUTH_FAIL_WRONG_CREDENTIAL',
  GET_CHEST_USECASE_WRONG_SECRET = 'GET_CHEST_USECASE_WRONG_SECRET'
}